schema_version: 1

context:
  version: "0.9.6"

package:
  name: mprocs
  version: ${{ version }}

source:
  url: https://github.com/pvolok/mprocs/archive/v${{ version }}.tar.gz
  sha256: 62488726fc5539772a41863428026f51b4c03d5ac27c56191775e5a721ae90c2

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then:
          - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path src
        else:
          - cargo auditable install --locked --no-track --bins --root %LIBRARY_PREFIX% --path src
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - cargo-auditable
    - make
    - python >=${{ python_min }}
  host:
    - if: linux
      then: libxcb

tests:
  - package_contents:
      bin:
        - mprocs
        - dk
      strict: true
  - script:
      - mprocs --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Run multiple commands in parallel
  homepage: https://github.com/pvolok/mprocs
  repository: https://github.com/pvolok/mprocs

extra:
  recipe-maintainers:
    - danielnachun
